name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  # schedule:
    # - cron: 35 15 * * 3

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 准备完成
      uses: actions/checkout@main

    - name: 下载架构编译配置文件
      run: |
        mkdir -p ./armv8
        wget -O ./armv8/.config https://raw.githubusercontent.com/Kwonelee/ZeroWrt-Native/refs/heads/main/armv8/00-config-rockchip --no-check-certificate

        FILE_PATH="./armv8/.config"
        if [ -f "$FILE_PATH" ] && [ -s "$FILE_PATH" ]; then
           content=$(cat ${GITHUB_WORKSPACE}/armv8/01-config-common \
                     ${GITHUB_WORKSPACE}/armv8/config-docker \
                     ${GITHUB_WORKSPACE}/armv8/config-package \
                     ${GITHUB_WORKSPACE}/armv8/config-version)
           configdata=$(echo "$content" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')
           echo -e "\\n$configdata" >> ./armv8/.config
           # 清除.config配置文件里面重复的配置项
           configdata2=$(cat ./armv8/.config)
           echo "$configdata2" | awk '!seen[$0]++ && NF > 0' > ./armv8/.config
        else
           echo "不处理数据。"
        fi

    - name: 同步配置
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        publish_branch: main
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"

    - name: 删除运行记录
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
        token: ${{ secrets.GH_TOKEN }}
